In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('ratings.csv')
df.head()

book_id  user_id  rating
0        1      314       5
1        1      439       3
2        1      588       5
3        1     1169       4
4        1     1185       4

In [4]:
array = np.loadtxt('ratings.csv',delimiter=',',skiprows = 706320, max_rows = 745559)
array

array([[7.1070e+03, 3.8650e+03, 4.0000e+00],
       [7.1070e+03, 4.4590e+03, 3.0000e+00],
       [7.1070e+03, 4.5410e+03, 4.0000e+00],
       ...,
       [1.0000e+04, 4.9383e+04, 5.0000e+00],
       [1.0000e+04, 5.0124e+04, 5.0000e+00],
       [1.0000e+04, 5.1328e+04, 1.0000e+00]])

In [6]:
array.shape

(275437, 3)

In [10]:
array.ravel()[np.random.choice(array.size, 190051, replace=False)] = np.nan
array

array([[       nan,        nan, 4.0000e+00],
       [7.1070e+03, 4.4590e+03, 3.0000e+00],
       [       nan, 4.5410e+03, 4.0000e+00],
       ...,
       [       nan, 4.9383e+04, 5.0000e+00],
       [       nan, 5.0124e+04,        nan],
       [       nan,        nan, 1.0000e+00]])

In [12]:
np.isnan(np.sum(array))

True

In [13]:
array.shape

(275437, 3)

In [14]:
from sklearn.impute import SimpleImputer

In [16]:
imp_con = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=10)

In [22]:
train = np.loadtxt('ratings.csv',delimiter=',', skiprows = 1, max_rows = 706320)
si1 = SimpleImputer(strategy='constant',fill_value=0)
train_imputed = si1.fit_transform(train)
test_imputed = si1.fit_transform(array)
print(train_imputed)
print(test_imputed)

[[1.000e+00 3.140e+02 5.000e+00]
 [1.000e+00 4.390e+02 3.000e+00]
 [1.000e+00 5.880e+02 5.000e+00]
 ...
 [7.107e+03 3.598e+03 4.000e+00]
 [7.107e+03 3.801e+03 3.000e+00]
 [7.107e+03 3.865e+03 4.000e+00]]
[[0.0000e+00 0.0000e+00 4.0000e+00]
 [7.1070e+03 4.4590e+03 3.0000e+00]
 [0.0000e+00 4.5410e+03 4.0000e+00]
 ...
 [0.0000e+00 4.9383e+04 5.0000e+00]
 [0.0000e+00 5.0124e+04 0.0000e+00]
 [0.0000e+00 0.0000e+00 1.0000e+00]]
